### PR TITLE
Breaking changes for v1

### LINKED ISSUE #52: [Question] Practical example of how to use the `when` field in RE
I can kind of struggle with using the `when` field for conditional transitions. Would it be possible to have an example that combine `when` and `actions` ?

### LINKED ISSUE #71: Roadmap to v1.0
Automa has been at the core of BioJulia for around four years, so it's probably about time it got the "finally stable" batch and a shiny 1.0 release. In particular I'm worried that too few people are really "into" Automa, and, if we lose interest or get too busy to work on BioJulia, the knowledge necessary to effective use Automa is lost.

At its core, a 1.0 release means that we settle on an *interface*. Hence, this issue is about how Automa should *feel*, not how it should *work*. For this part, I would appreciate getting feedback from as many users as possible: What did you find hardest about Automa? How could it be made nicer to use? Could the interface be simplified?

A few suggestions:
- [x] `CodeGenContext` should be optional, because people shouldn't need to go deep into Automa to be able to use it. It should default to something equivalent to `CodeGenContext(:goto)` or maybe just `CodeGenContext()`
- [x] Perhaps `p_eof = sizeof(mem); p_end = sizeof(mem)` should be included in `gen_init_code()` to make it easier?
- [x] Add the error handling in #64 when an unexpected input is seen. Allow users to paste this generated code into their functions.
- [x] Add this error handling to default implementations like `generate_validator_function`
- [ ] Rewrite Automa.RegExp if possible

There are a few non-API things I would like to have done before 1.0, but these are not critical to get done before v1.0.
- [x] Merge `:goto` and `:simd` generator, optionally improving the underlying codegen ( #53 )
- [x] Improve docs with examples (which implies we need to have nailed the interface *before then*.
- [x] Docs: Explain very clearly that Automa is byte-oriented
- [ ] Docs: Advice using function calls as Expr objects, explain why, and amend the examples
- [x] Add extra debugging capabilities and general quality-of-life improvements (#64 )
- [x] Enforce the symbols in the passed Dict in `generate_exec_code` are the same as those in the Machine.

I'm envisioning tagging v1.0 some time before end of northern hemisphere summer 2022.

### LINKED ISSUE #80: Multi-bytes characters trigger actions multiple times
For multi-bytes unicode characters (e.g. `ϕ`) the actions are triggered once for each byte, instead of once for each character. This is unexpected and rather hard to work with.

```julia
using Automa
import Automa.RegExp: @re_str

const re = Automa.RegExp

anything = re"."
anything.actions[:exit] = [:info]
machine = Automa.compile(re.rep(anything))

Automa.execute(machine, "ϕ")  # return (0, [:info, :info])
```

### LINKED ISSUE #82: Factor out transcoding streams dependency
If Automa ever gets easier to use, it might be more generally useful than just creating biological readers. In that case, there will be lots of use cases for it to operate on memory buffers, where the TranscodingStreams dependency is not needed.

### LINKED ISSUE #91: Automa has too many code generators
Currently Automa has the following code generators:
* table code generator
* inline code generator
* goto code generator
* simd code generator
* tokenizer code generator

There is no good reason for this. I think it should be possible to cut it down to two full code generators and two modifications of these:
* Table code generator, with tokenizer codegen using most of its internals
* SIMD code generator, with fallbacks when there is no SIMD.

Having the choice b/w table and SIMD code generator can be good, because the latter generates much more code.

### LINKED ISSUE #102: Taking preconditions seriously
Automa already has _preconditions_ - these are named `Expr` objects attached to edges, similar to actions. When encountering an edge, its code generators first check the byteset membership, then it evaluated the precondition's `Expr`, which must evaluate to a Bool, and takes the edge if evaluated to `true`. Preconditions are attached to regex, and apply to all transitions inside that regex.

In other words, preconditions enable you to state: Only move within this regex if this condition is fulfilled. This is particularly useful when dealing with ambiguous DFAs that can be disambiguated using preconditions - essentially, this is like manually inserting an if-statement into the finite state machine.

However, Automa's support for preconditions is shaky, and frankly, I believe, might be buggy. I did some experiments that seemed to suggest that Automa would collapse two NFA paths with different preconditions... which sort of defeats the purpose.
This needs to be thoroughly tested

- [ ] Enable preconditions on "enter" only, in addition to the already existing "all"
- [ ] Make sure not to collapse NFA paths with disambiguating preconditions on DFA creation. Then remove precond check in DFA validation code path
- [ ] Have table-based generators support predond. Simply insert an if statement after state transition.
- [ ] Check that edges with preconditions do not allow SIMD loops (just to be sure!)
- [ ] Test, test, test and test more

In particular, I want something like this to work:
```
a1 = re"A"
a2 = re"A"
b1 = re"B"
b2 = re"B"
b2.when = :foo
c1 = re"C"
c1.actions[:enter] = [:bar]
Automa.compile((a1 * b1 * c1) | (a2 * b2 * re"C"))
```
, i.e. where otherwise indistinguishable paths a1-b1-c1 and a2-b2-c2 with conflicting actions are disambiguated by a precondition on b2.

### LINKED ISSUE #111: Slow compilation speed
Automa is a compiler that compiles regular expressions into Julia code.
While it produces fast code, the compiler itself (i.e. Automa) is slow. Having worked on the code, I can tell you that it's absolutely not optimised for compilation speed.
I'm not sure how big of a deal this is. Presumably all the heavy lifting is done in the precompilation stage.
Nonetheless, it would be nice to profile codegen from a complex regex to see just where the bottlenecks are.

### LINKED ISSUE #115: Looping regex can be given a final action
MWE:
```
julia> Automa.execute(compile(onfinal!(re"a+", :x)), "aaa")
(0, [:x, :x, :x])
```

On `master` syntax:
```
julia> Automa.execute(Automa.compile((x = Automa.RegExp.parse("a+"); x.actions[:final] = [:x]; x)), "aaa")
(0, [:x, :x, :x])
```

The problem here is that in the regex `re"a+"`, it's not clear what the final byte is. This should be fixed in `re2nfa`

### LINKED ISSUE #116: Issues with Tokenizer
There are a few things I'd like to address before v1:

* Should the Tokenizer even exist? It's fairly easy to make one yourself. If it should exist, perhaps it should be even more high-level, simply creating an enum and returning `(enum, start:end)`, only for byte buffers (no need to parse IOs with Tokenizers)
* The goto generator should work with tokenizers. Noone wants the slow tokenizer.
* Perhaps do a full rewrite, and if so, also remove the special case for `:final` actions in `re2nfa` that special-cases tokenizer actions. Maybe there is little need for a `Tokenizer` object - perhaps it could just be a function that takes a series of action-less `regex`, which then compiles an ordinary `Machine`.

### PR DESCRIPTION
**Pull request by jakobnissen**
Supersedes #95 

## Todo
* Fixup the commit history (review if fixes are necessary)
* Get test coverage near 100%
* Figure out if you can get CI on M1 mac

Closes #52 
Closes #71 
Closes #80 
Closes #82 
Closes #91 
Closes #102 
Closes #111 
Closes #115 
Closes #116

### CODE REVIEW

**Comment by kescobo** [comment]
FYI, it is still on my radar to kick the tires of this. I think early next month is probably realistic.

**Comment by kescobo** [comment]
> I think early next month is probably realistic.

I was wroooong :sob: 

Do you have a timeline for when you want this merged. Realistically, I need some pressure to make it a priority

**Comment by jakobnissen** [comment]
Haha don't I know that feeling. I also expected I would be done with this branch in the summer of 2022, so... :sweat_smile: 
My holidays start today, so I expect I can finish the work before the holidays are over in about 3 weeks. Maybe. No promises. Although if you want a deadline, then July 17th is probably when I'll pick this work up and finish it.

**Comment by jakobnissen** [comment]
Ok I'm going to merge this now and release Automa v1. @kescobo

**Pull request merged**
