### PR TITLE
Work on deploying docs via github actions

### LINKED ISSUE #70: Add Documenter-based automatic documentation hosting
I removed documentation hosting in one of the last commits (and it didn't work before, anyway), so that needs to be restored

### PR DESCRIPTION
**Pull request by kescobo**
will close #70

### CODE REVIEW

**Comment by kescobo** [comment]
Alright - looks like this is working - see https://biojulia.net/Automa.jl/previews/PR72/

**Comment by jakobnissen** [comment]
All looks good to me

**Comment by kescobo** [comment]
Looks like `latest` still goes to v0.6 - might be worth making a minor release (eg `0.8.1`) to kick off the action. I'm not sure if there's a way to do it manually

**Comment by jakobnissen** [comment]
Let's do that.

**Comment by kescobo** [comment]
Success! As of #74  #75 https://biojulia.net/Automa.jl/v0.8/

**Pull request merged**
